"""Standalone HTML report: one file, inline CSS, no script, no external resource.

A restrictive Content-Security-Policy is embedded as defense in depth: even if some student text
escaped escaping, the browser would refuse to run scripts or load anything.
"""
from __future__ import annotations

from datetime import timezone

from premoulinette.report.common import (
    CATEGORY_LABELS,
    DISCLAIMER,
    EXERCISE_STATUS_LABELS,
    fmt_pct,
    group_issues_by_file,
    location_text,
    provenance_label,
)
from premoulinette.report.html_checks import badge, check_card, esc
from premoulinette.report.html_style import CSS
from premoulinette.results.models import AnalysisReport, ScoreSummary

_CSP = "default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'"


def render_html(report: AnalysisReport) -> str:
    body = "".join([
        _header(report),
        _verdict(report.score),
        f'<p class="disclaimer">{esc(DISCLAIMER)}</p>',
        _categories(report.score),
        _exercises(report.score),
        _issues(report),
        _warnings(report),
        _environment(report),
        _all_checks(report),
        f"<footer><p>{esc(DISCLAIMER)}</p><p>Generated by PréMoulinette (local pre-grader).</p></footer>",
    ])
    return (
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        f"<meta http-equiv=\"Content-Security-Policy\" content=\"{_CSP}\">\n"
        f"<title>PréMoulinette report — {esc(report.subject.title)}</title>\n"
        f"<style>{CSS}</style>\n</head>\n<body>\n<main class=\"page\">{body}</main>\n</body>\n</html>\n"
    )


def _section(title: str, content: str) -> str:
    return f"<section><h2>{esc(title)}</h2>{content}</section>"


def _table(headers: list[str], rows: list[list[str]]) -> str:
    """Cells must already be escaped HTML."""
    head = "".join(f"<th>{esc(h)}</th>" for h in headers)
    body = "".join("<tr>" + "".join(f"<td>{cell}</td>" for cell in row) + "</tr>" for row in rows)
    return f'<div class="table-wrap"><table class="grid"><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></div>'


def _bar(score: float | None) -> str:
    value = max(0.0, min(100.0, score or 0.0))
    level = "good" if value >= 100.0 else ("mid" if value >= 50.0 else "bad")
    return f'<div class="bar"><span class="bar-fill fill-{level}" style="width:{value:.1f}%"></span></div>'


def _header(r: AnalysisReport) -> str:
    created = r.created_at.astimezone(timezone.utc) if r.created_at.tzinfo else r.created_at
    mode = "Docker sandbox" if r.sandbox.mode == "docker" else "Developer mode sandbox (local)"
    return (
        '<header><div class="brand">PréMoulinette · pre-submission report</div>'
        f"<h1>{esc(r.subject.title)}</h1>"
        f'<p class="meta">Project <b>{esc(r.project.name)}</b> · Analysis #{esc(r.number)} · '
        f"{esc(f'{created:%Y-%m-%d %H:%M}')} UTC · {esc(f'{r.duration_ms / 1000:.1f}')} s · {esc(mode)}</p></header>"
    )


def _verdict(s: ScoreSummary) -> str:
    bonus = (f"{fmt_pct(s.bonus_completion)}", f"Bonus ({s.bonus_passed}/{s.bonus_total})") \
        if s.bonus_completion is not None else ("—", "No bonus")
    kpis = [
        (fmt_pct(s.readiness), f"Readiness Score ({s.mandatory_passed}/{s.mandatory_total} mandatory checks)"),
        (str(s.mandatory_failures), "Mandatory failures"),
        bonus,
        (s.confidence.capitalize(), "Confidence"),
    ]
    kpi_html = "".join(
        f'<div class="kpi"><span class="kpi-value">{esc(v)}</span><span class="kpi-label">{esc(label)}</span></div>'
        for v, label in kpis
    )
    reasons = ""
    if s.confidence_reasons:
        reasons = '<ul class="reasons">' + "".join(f"<li>{esc(x)}</li>" for x in s.confidence_reasons) + "</ul>"
    return (
        f'<section class="verdict verdict-{esc(s.verdict)}" role="status">'
        f'<div class="verdict-title">{esc(s.verdict_title)}</div>'
        f'<p class="verdict-msg">{esc(s.verdict_message)}</p>'
        f"{_bar(s.readiness)}<div style=\"height:12px\"></div>"
        f'<div class="kpis">{kpi_html}</div>{reasons}</section>'
    )


def _categories(s: ScoreSummary) -> str:
    if not s.categories:
        return _section("Score by category", '<p class="muted">No mandatory check.</p>')
    rows = "".join(
        f'<div class="bar-row"><span>{esc(c.label)}</span>{_bar(c.score)}'
        f'<span class="bar-value">{c.passed}/{c.total} · {esc(fmt_pct(c.score))}'
        + (f" · {c.warnings} warning(s)" if c.warnings else "") + "</span></div>"
        for c in s.categories
    )
    return _section("Score by category", f'<div class="bars">{rows}</div>')


def _exercises(s: ScoreSummary) -> str:
    if not s.exercises:
        return ""
    rows = [
        [
            esc(e.title) + (' <span class="badge b-bonus">BONUS</span>' if e.bonus else ""),
            f"<code>{esc(e.file)}</code>",
            badge(e.status, EXERCISE_STATUS_LABELS.get(e.status, e.status)),
            f"{e.passed}/{e.total}",
            esc(fmt_pct(e.score)),
            str(e.issues),
        ]
        for e in s.exercises
    ]
    return _section("Exercises", _table(["Exercise", "File", "Status", "Passed", "Score", "Issues"], rows))


def _issues(r: AnalysisReport) -> str:
    groups = group_issues_by_file(r)
    if not groups:
        return _section("Issues by file", '<p class="muted">No issue found.</p>')
    content = "".join(
        f'<div class="file-group"><h3><code>{esc(path)}</code> <span class="muted">({len(checks)})</span></h3>'
        + "".join(check_card(c) for c in checks) + "</div>"
        for path, checks in groups
    )
    return _section("Issues by file", content)


def _warnings(r: AnalysisReport) -> str:
    items = list(r.pipeline_warnings) + list(r.sandbox.warnings)
    if not items:
        return ""
    return _section("Warnings", "<ul>" + "".join(f"<li>{esc(x)}</li>" for x in items) + "</ul>")


def _kv(rows: list[tuple[str, str]]) -> str:
    return '<dl class="kv">' + "".join(f"<dt>{esc(k)}</dt><dd>{v}</dd>" for k, v in rows) + "</dl>"


def _environment(r: AnalysisReport) -> str:
    p, sb, spec = r.project, r.sandbox, r.spec
    project = _kv([
        ("Project", esc(p.name)),
        ("Source", esc(p.source_kind) + (f" · <code>{esc(p.path)}</code>" if p.path else "")),
        ("Detected root", f"<code>{esc(p.detected_root)}</code>" if p.detected_root else "(top level)"),
        ("Files", f"{p.file_count} ({p.python_files} Python)"),
        *([("Root detection", esc(p.root_note))] if p.root_note else []),
    ])
    git = p.git
    if git is None or not git.is_repo:
        git_html = f'<p class="muted">{esc(git.error if git and git.error else "Not a git repository.")}</p>'
    else:
        git_html = _kv([
            ("Branch", esc(git.branch or "—")),
            ("HEAD", f"<code>{esc(git.head)}</code>" if git.head else "—"),
            ("Last commit", esc(" ".join(x for x in (git.last_commit_date, git.last_commit_message) if x) or "—")),
            ("Working tree", "dirty" if git.dirty else "clean"),
            ("Untracked", esc(", ".join(git.untracked) or "none")),
        ])
    sandbox = _kv([
        ("Mode", "Docker (safe mode)" if sb.mode == "docker" else "Local (developer mode)"),
        ("Image", f"<code>{esc(sb.image)}</code>" if sb.image else "—"),
        ("Python", esc(sb.python_version or "—")),
        ("Network", "enabled" if sb.network else "disabled"),
    ])
    subject = _kv([
        ("Subject", esc(r.subject.title)),
        ("Source file", esc(r.subject.source_name or "—")),
        ("Parser", esc(r.subject.parser)),
        ("Reviewed by user", "yes" if spec.metadata.reviewed_by_user else "no"),
    ])
    return _section(
        "Repository & environment",
        f"<h3>Project</h3>{project}<h3>Git</h3>{git_html}<h3>Sandbox</h3>{sandbox}<h3>Subject</h3>{subject}",
    )


def _all_checks(r: AnalysisReport) -> str:
    rows = [
        [
            badge(c.status) + (f' <span class="sev sev-{esc(c.severity)}">{esc(c.severity)}</span>'
                               if c.severity and c.status != "pass" else ""),
            esc(CATEGORY_LABELS.get(c.category, c.category)),
            f"{esc(c.title)}<br><code>{esc(c.id)}</code>",
            f"<code>{esc(loc)}</code>" if (loc := location_text(c)) else "",
            f'<span class="prov prov-{esc(c.origin.provenance)}">{esc(provenance_label(c))}</span>',
            esc(c.message),
        ]
        for c in r.checks
    ]
    if not rows:
        return _section("All checks", '<p class="muted">No check was run.</p>')
    return _section("All checks", _table(["Status", "Category", "Check", "Location", "Origin", "Result"], rows))
